### ISSUE TITLE
object tuple can't be used in 'await' expression

### ISSUE THREAD

**Issue by bmaehr** [bieniu/brother#184]
2023-02-25 23:18:15.010 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Drucker9120 for brother
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/brother/__init__.py", line 33, in async_setup_entry
    brother = await Brother.create(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/brother/__init__.py", line 95, in create
    await instance.initialize()
  File "/srv/homeassistant/lib/python3.11/site-packages/brother/__init__.py", line 121, in initialize
    _, errstatus, errindex, _ = await get_result
                                ^^^^^^^^^^^^^^^^
TypeError: object tuple can't be used in 'await' expression

**Comment by bieniu** [comment]
Please fill up the form or this issue will be closed. Thanks.

**Comment by bmaehr** [comment]
Issue is in this line https://github.com/bieniu/brother/blob/77a3146547a0341523517a92f46df8fda8a2f141/brother/__init__.py#L122 I don't know why it is not allowed - I"m not a python developer.

**Comment by bieniu** [comment]
Which version of the package?

**Comment by IggePop** [comment]
Same error here.
Version 2.2.0, Python 3.11.1

**Comment by IggePop** [comment]
I made a PR: https://github.com/bieniu/brother/pull/191

**Comment by bieniu** [comment]
Fixed via https://github.com/bieniu/brother/pull/191
